# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "This lane tests the Recipes-App"
  before_all do 
    setup_circle_ci
  end

  lane :test do
    begin
    # add actions here: https://docs.fastlane.tools/actions
      setup_ci if ENV['CI']

      increment_build_number
      swiftlint(config_file: ".swiftlint.yml")
      
      scan(
        project: "Recipes.xcodeproj",
        scheme: "Recipes",
        device: "iPhone 13 Pro (15.5)",
        testplan: "Recipes",
        xcodebuild_formatter: "xcbeautify"
      )

      version = get_version_number(xcodeproj: "Recipes.xcodeproj")
      build_number = get_build_number(xcodeproj: "Recipes.xcodeproj")

      onSuccess(version, build_number)
    rescue => exception
      version = get_version_number(xcodeproj: "Recipes.xcodeproj")
      build_number = get_build_number(xcodeproj: "Recipes.xcodeproj")

      onError(exception, version, build_number)
    end
  end
end

def onSuccess(version, build_number)
  slack(
    message: "Successfully built and tested Recipes App",
    success: true,
    slack_url: ENV["SLACK_URL"],
    default_payloads: [
            :last_git_commit_hash
        ],
        payload: {
            "Build Date" => Time.new.to_s,
            "Version" => version,
            "Build Number" => build_number
        }
  )
end

def onError(exception) 
  slack(
    message: "Something went wrong",
    success: false, 
    slack_url: ENV["SLACK_URL"],
    attachment_properties: {
      fields: [
        {
          title: "Build Date",
          value: Time.new.to_s
        },
        {
          title: "Version",
          value: version
        },
        {
          title: "Build Number",
          value: build_number
        },
        {
          title: "Error message",
          value: exception.to_s,
          short: false
        }
      ]
    }
  )
end
