# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "This lane tests the Recipes-App"
  before_all do 
    setup_circle_ci
  end

  desc "Use Swiftlint for a clean coding style"
  lane :lint do
    swiftlint(config_file: ".swiftlint.yml")
  end

  desc "Run all tests"
  lane :test do |options|
    begin
    # add actions here: https://docs.fastlane.tools/actions
      increment_build_number
      scan(
        project: "Recipes.xcodeproj",
        scheme: "Recipes",
        device: "iPhone 13 Pro (15.5)",
        testplan: "Recipes",
        xcodebuild_formatter: "xcbeautify"
      )

      version = get_version_number(xcodeproj: "Recipes.xcodeproj")
      build_number = get_build_number(xcodeproj: "Recipes.xcodeproj")

      SLACK_URL = options[:slack]
      onSuccess(version, build_number, SLACK_URL)
    rescue => exception
      version = get_version_number(xcodeproj: "Recipes.xcodeproj")
      build_number = get_build_number(xcodeproj: "Recipes.xcodeproj")

      SLACK_URL = options[:slack]
      onError(exception, version, build_number, SLACK_URL)
    end
  end
end

def onSuccess(version, build_number, SLACK_URL)
  slack(
    message: "Successfully built and tested Recipes App",
    success: true,
    slack_url: SLACK_URL,
    default_payloads: [
            :last_git_commit_hash
        ],
        payload: {
            "Build Date" => Time.new.to_s,
            "Version" => version,
            "Build Number" => build_number
        }
  )
end

def onError(exception, version, build_number, SLACK_URL) 
  slack(
    message: "Something went wrong",
    success: false, 
    slack_url: SLACK_URL,
    attachment_properties: {
      fields: [
        {
          title: "Build Date",
          value: Time.new.to_s
        },
        {
          title: "Version",
          value: version
        },
        {
          title: "Build Number",
          value: build_number
        },
        {
          title: "Error message",
          value: exception.to_s,
          short: false
        }
      ]
    }
  )
end
